{
    "org.apache.commons.math.optimization.MultiStartUnivariateRealOptimizerTest::testQuinticMin": {
        "begin_line_no": 55,
        "end_line_no": 100,
        "file_path": "src/test/java/org/apache/commons/math/optimization/MultiStartUnivariateRealOptimizerTest.java",
        "to": [
            "    @Test\n    public void testQuinticMin$catena_5() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                                  /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_4() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        assertEquals(-0.2719561270319131, result, 1.0e-13);                                                 /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_0() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            fail(\"an exception should have been thrown\");                                                   /***** ORIGINAL ASSERTION IS HERE *****/\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_1() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            fail(\"wrong exception caught\");                                                                 /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_2() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            fail(\"an exception should have been thrown\");                                                   /***** ORIGINAL ASSERTION IS HERE *****/\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_3() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            fail(\"wrong exception caught\");                                                                 /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_6() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                          /***** ORIGINAL ASSERTION IS HERE *****/\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_7() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                     /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_8() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        assertTrue(minimizer.getEvaluations()    >= 120);                                                   /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMin$catena_11() throws MathException {\n        // The quintic function has zeros at 0, +-0.5 and +-1.\n        // The function has extrema (first derivative is zero) at 0.27195613 and 0.82221643,\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        underlying.setRelativeAccuracy(1e-15);\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(4312000053L);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 5, g);\n        minimizer.setAbsoluteAccuracy(10 * minimizer.getAbsoluteAccuracy());\n        minimizer.setRelativeAccuracy(10 * minimizer.getRelativeAccuracy());\n\n        try {\n            minimizer.getOptima();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try {\n            minimizer.getOptimaValues();\n            try{ fail(\"an exception should have been thrown\");                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (IllegalStateException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n\n        double result = minimizer.optimize(f, GoalType.MINIMIZE, -0.3, -0.2);\n        try{ assertEquals(-0.2719561270319131, result, 1.0e-13);                                            }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.2719561270319131, minimizer.getResult(), 1.0e-13);                             }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(-0.04433426954946637, minimizer.getFunctionValue(), 1.0e-13);                     }catch(Throwable __SHOULD_BE_IGNORED){}\n\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 0; i < optima.length; ++i) {\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations()    >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 170);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() >= 120);                                              }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertTrue(minimizer.getIterationCount() <= 170);                                                   /***** ORIGINAL ASSERTION IS HERE *****/\n    }"
        ]
    },
    "org.apache.commons.math.optimization.MultiStartUnivariateRealOptimizerTest::testSinMin": {
        "begin_line_no": 34,
        "end_line_no": 53,
        "file_path": "src/test/java/org/apache/commons/math/optimization/MultiStartUnivariateRealOptimizerTest.java",
        "to": [
            "    @Test\n    public void testSinMin$catena_0() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(44428400075l);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 10, g);\n        minimizer.optimize(f, GoalType.MINIMIZE, -100.0, 100.0);\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 1; i < optima.length; ++i) {\n            double d = (optima[i] - optima[i-1]) / (2 * Math.PI);\n            assertTrue (Math.abs(d - Math.rint(d)) < 1.0e-8);                                               /***** ORIGINAL ASSERTION IS HERE *****/\n            try{ assertEquals(-1.0, f.value(optima[i]), 1.0e-10);                                           }catch(Throwable __SHOULD_BE_IGNORED){}\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations() > 150);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations() < 250);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testSinMin$catena_1() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(44428400075l);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 10, g);\n        minimizer.optimize(f, GoalType.MINIMIZE, -100.0, 100.0);\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 1; i < optima.length; ++i) {\n            double d = (optima[i] - optima[i-1]) / (2 * Math.PI);\n            try{ assertTrue (Math.abs(d - Math.rint(d)) < 1.0e-8);                                          }catch(Throwable __SHOULD_BE_IGNORED){}\n            assertEquals(-1.0, f.value(optima[i]), 1.0e-10);                                                /***** ORIGINAL ASSERTION IS HERE *****/\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertTrue(minimizer.getEvaluations() > 150);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations() < 250);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testSinMin$catena_2() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(44428400075l);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 10, g);\n        minimizer.optimize(f, GoalType.MINIMIZE, -100.0, 100.0);\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 1; i < optima.length; ++i) {\n            double d = (optima[i] - optima[i-1]) / (2 * Math.PI);\n            try{ assertTrue (Math.abs(d - Math.rint(d)) < 1.0e-8);                                          }catch(Throwable __SHOULD_BE_IGNORED){}\n            try{ assertEquals(-1.0, f.value(optima[i]), 1.0e-10);                                           }catch(Throwable __SHOULD_BE_IGNORED){}\n            assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                     /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n        try{ assertTrue(minimizer.getEvaluations() > 150);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations() < 250);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testSinMin$catena_3() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer underlying = new BrentOptimizer();\n        JDKRandomGenerator g = new JDKRandomGenerator();\n        g.setSeed(44428400075l);\n        MultiStartUnivariateRealOptimizer minimizer =\n            new MultiStartUnivariateRealOptimizer(underlying, 10, g);\n        minimizer.optimize(f, GoalType.MINIMIZE, -100.0, 100.0);\n        double[] optima = minimizer.getOptima();\n        double[] optimaValues = minimizer.getOptimaValues();\n        for (int i = 1; i < optima.length; ++i) {\n            double d = (optima[i] - optima[i-1]) / (2 * Math.PI);\n            try{ assertTrue (Math.abs(d - Math.rint(d)) < 1.0e-8);                                          }catch(Throwable __SHOULD_BE_IGNORED){}\n            try{ assertEquals(-1.0, f.value(optima[i]), 1.0e-10);                                           }catch(Throwable __SHOULD_BE_IGNORED){}\n            try{ assertEquals(f.value(optima[i]), optimaValues[i], 1.0e-10);                                }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        assertTrue(minimizer.getEvaluations() > 150);                                                       /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertTrue(minimizer.getEvaluations() < 250);                                                  }catch(Throwable __SHOULD_BE_IGNORED){}\n    }"
        ]
    },
    "org.apache.commons.math.optimization.univariate.BrentOptimizerTest::testQuinticMinStatistics": {
        "begin_line_no": 85,
        "end_line_no": 115,
        "file_path": "src/test/java/org/apache/commons/math/optimization/univariate/BrentOptimizerTest.java",
        "to": [
            "    @Test\n    public void testQuinticMinStatistics$catena_0() throws MathException {\n        // The function has local minima at -0.27195613 and 0.82221643.\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setRelativeAccuracy(1e-10);\n        minimizer.setAbsoluteAccuracy(1e-11);\n\n        final DescriptiveStatistics[] stat = new DescriptiveStatistics[3];\n        for (int i = 0; i < stat.length; i++) {\n            stat[i] = new DescriptiveStatistics();\n        }\n\n        final double min = -0.75;\n        final double max = 0.25;\n        final int nSamples = 200;\n        final double delta = (max - min) / nSamples;\n        for (int i = 0; i < nSamples; i++) {\n            final double start = min + i * delta;\n            stat[0].addValue(minimizer.optimize(f, GoalType.MINIMIZE, min, max, start));\n            stat[1].addValue(minimizer.getIterationCount());\n            stat[2].addValue(minimizer.getEvaluations());\n        }\n\n        final double meanOptValue = stat[0].getMean();\n        final double medianIter = stat[1].getPercentile(50);\n        final double medianEval = stat[2].getPercentile(50);\n        assertTrue(meanOptValue > -0.27195612812 && meanOptValue < -0.27195612811);                         /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertEquals(medianIter, 17, Math.ulp(1d));                                                    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(medianEval, 18, Math.ulp(1d));                                                    }catch(Throwable __SHOULD_BE_IGNORED){}\n    }",
            "    @Test\n    public void testQuinticMinStatistics$catena_1() throws MathException {\n        // The function has local minima at -0.27195613 and 0.82221643.\n        UnivariateRealFunction f = new QuinticFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setRelativeAccuracy(1e-10);\n        minimizer.setAbsoluteAccuracy(1e-11);\n\n        final DescriptiveStatistics[] stat = new DescriptiveStatistics[3];\n        for (int i = 0; i < stat.length; i++) {\n            stat[i] = new DescriptiveStatistics();\n        }\n\n        final double min = -0.75;\n        final double max = 0.25;\n        final int nSamples = 200;\n        final double delta = (max - min) / nSamples;\n        for (int i = 0; i < nSamples; i++) {\n            final double start = min + i * delta;\n            stat[0].addValue(minimizer.optimize(f, GoalType.MINIMIZE, min, max, start));\n            stat[1].addValue(minimizer.getIterationCount());\n            stat[2].addValue(minimizer.getEvaluations());\n        }\n\n        final double meanOptValue = stat[0].getMean();\n        final double medianIter = stat[1].getPercentile(50);\n        final double medianEval = stat[2].getPercentile(50);\n        try{ assertTrue(meanOptValue > -0.27195612812 && meanOptValue < -0.27195612811);                    }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertEquals(medianIter, 17, Math.ulp(1d));                                                         /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertEquals(medianEval, 18, Math.ulp(1d));                                                    }catch(Throwable __SHOULD_BE_IGNORED){}\n    }"
        ]
    },
    "org.apache.commons.math.optimization.univariate.BrentOptimizerTest::testSinMin": {
        "begin_line_no": 40,
        "end_line_no": 69,
        "file_path": "src/test/java/org/apache/commons/math/optimization/univariate/BrentOptimizerTest.java",
        "to": [
            "    @Test\n    public void testSinMin$catena_0() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        assertEquals(200, minimizer.getMaxEvaluations());                                                                            /***** ORIGINAL ASSERTION IS HERE *****/\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_1() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            fail(\"an exception should have been thrown\");                                                                            /***** ORIGINAL ASSERTION IS HERE *****/\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_2() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            fail(\"wrong exception caught\");                                                                                          /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_4() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertTrue(minimizer.getIterationCount() <= 50);                                                                             /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_6() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertTrue(minimizer.getIterationCount() <= 50);                                                                             /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_7() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertTrue(minimizer.getEvaluations()    <= 100);                                                                            /***** ORIGINAL ASSERTION IS HERE *****/\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_8() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        assertTrue(minimizer.getEvaluations()    >=  15);                                                                            /***** ORIGINAL ASSERTION IS HERE *****/\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_9() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            fail(\"an exception should have been thrown\");                                                                            /***** ORIGINAL ASSERTION IS HERE *****/\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }",
            "    @Test\n    public void testSinMin$catena_10() throws MathException {\n        UnivariateRealFunction f = new SinFunction();\n        UnivariateRealOptimizer minimizer = new BrentOptimizer();\n        minimizer.setMaxEvaluations(200);\n        try{ assertEquals(200, minimizer.getMaxEvaluations());                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try {\n            minimizer.getResult();\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (NoDataException ise) {\n            // expected\n        } catch (Exception e) {\n            try{ fail(\"wrong exception caught\");                                                                                     }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 4, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertEquals(3 * Math.PI / 2, minimizer.optimize(f, GoalType.MINIMIZE, 1, 5), 10 * minimizer.getRelativeAccuracy());    }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getIterationCount() <= 50);                                                                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    <= 100);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        try{ assertTrue(minimizer.getEvaluations()    >=  15);                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        minimizer.setMaxEvaluations(10);\n        try {\n            minimizer.optimize(f, GoalType.MINIMIZE, 4, 5);\n            try{ fail(\"an exception should have been thrown\");                                                                       }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (FunctionEvaluationException fee) {\n            // expected\n        } catch (Exception e) {\n            fail(\"wrong exception caught\");                                                                                          /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n    }"
        ]
    }
}