{
    "org.apache.commons.jxpath.ri.model.beans.BadlyImplementedFactoryTest::testBadFactoryImplementation": {
        "begin_line_no": 59,
        "end_line_no": 66,
        "file_path": "src/test/org/apache/commons/jxpath/ri/model/beans/BadlyImplementedFactoryTest.java",
        "to": [
            "    public void testBadFactoryImplementation$catena_1() {\n        try {\n            context.createPath(\"foo/bar\");\n            try{ fail(\"should fail with JXPathException caused by JXPathAbstractFactoryException\");         }catch(Throwable __SHOULD_BE_IGNORED){}\n        } catch (JXPathException e) {\n            assertTrue(e.getCause() instanceof JXPathAbstractFactoryException);                             /***** ORIGINAL ASSERTION IS HERE *****/\n        }\n    }",
            "    public void testBadFactoryImplementation$catena_0() {\n        try {\n            context.createPath(\"foo/bar\");\n            fail(\"should fail with JXPathException caused by JXPathAbstractFactoryException\");              /***** ORIGINAL ASSERTION IS HERE *****/\n        } catch (JXPathException e) {\n            try{ assertTrue(e.getCause() instanceof JXPathAbstractFactoryException);                        }catch(Throwable __SHOULD_BE_IGNORED){}\n        }\n    }"
        ]
    }
}