Traceback (most recent call last):
  File "run.py", line 17, in task
    raise Exception('{} is a deprecated bug'.format(bug_id))
Exception: Time_21 is a deprecated bug
